title: "Mark Sowell | CCSM Elite, CEH Master, & Cybersecurity Expert"
description: Mark Sowell is a Check Point Professional Services Consultant, Penetration Tester, Harmony Endpoint SME, CCSM Elite, CEH Master, & Cybersecurity Expert. 
baseurl: ""
url: "https://marksowell.com"
email: mark@marksowell.com

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
twitter:
  username: marksowell
logo: "/favicon.ico" # site wide logo for use on social settings
facebook:
 publisher: marksowell
lang: en_US

username: Mark Sowell
user_description: Check Point Professional Services Consultant, Penetration Tester, Harmony Endpoint SME, CCSM Elite, CEH Master, & Cybersecurity Expert
user_title: Check Point Professional Services Consultant, Penetration Tester, Harmony Endpoint SME, CCSM Elite, CEH Master, & Cybersecurity Expert
github_username:  marksowell
twitter_username: marksowell

author:
    twitter: marksowell

social:
  name: Mark Sowell
  links:
    - https://twitter.com/marksowell
    - https://www.facebook.com/marksowell
    - https://www.linkedin.com/in/marksowell
    - https://github.com/marksowell
    - https://keybase.io/marksowell

google-analytics:
  id: "UA-30849249-1"

exclude: ['package.json', 'src' , 'node_modules']
