title: Mark Sowell - Cybersecurity Consultant in Denver, CO
description: Mark Sowell, CEH Master, CCSM - Check Point Professional Services Consultant, Certified Ethical Hacker (Master), Check Point Certified Security Master, & Cybersecurity Expert.
baseurl: ""

username: Mark Sowell
user_description: Check Point Professional Services Consultant, Certified Ethical Hacker (Master), Check Point Certified Security Master, & Cybersecurity Expert
user_title: Check Point Professional Services Consultant, Certified Ethical Hacker (Master), Check Point Certified Security Master, & Cybersecurity Expert
github_username:  marksowell

google-analytics:
  id: "UA-30849249-1"

exclude: ['package.json', 'src' , 'node_modules']
