title: Christoforos Petrou
description: Welcome to my personal space on the internet ðŸ˜€
baseurl: ""

username: Christoforos Petrou
user_description: Software Engineer & Information Security Enthusiast
user_title: Software Engineer & Information Security Enthusiast
github_username:  chrispetrou

google-analytics:
  id: "UA-143541693-1"

exclude: ['package.json', 'src' , 'node_modules']
